### PR TITLE
Handle cell vars in closures and update m{in,ax} impls

### PR DESCRIPTION
**Pull request by stuartarchibald**
This adds a patch to closure inlining that ostensibly handles
cell variables. This allows for inlining more arbitrary closures
during IR manipulations in the pipeline.

It also rewrites the argm{in,ax} and m{in,ax} to use this
functionality.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@ehsantn I'm not 100% sure of the validity of this change. I suspect more may need to be done as there's `ir.Const` containing builtins now, however, this seems to work but quite possibly for the wrong reasons!

**Comment by ninegua** [comment]
Thanks for the PR. It looks plausible, but I wonder in what context does this `tuple` and `cell_contents` arise as closure environment? Why did Python behave like this when it already had a way using `build_tuple`?

**Comment by stuartarchibald** [comment]
@ninegua This is what I was puzzled over too and it was the root of my noted uncertainty, I also was wondering why this didn't go via the path you describe. I think it can be summarised as the difference between asking the inliner to inline an enclosing function and asking it to inline and instance of the enclosed function.

The reason I attempted this was to allow the type based specialisation of function to be determined at runtime and that specialised instance to be inlined thus avoiding using `llvmlite` and `IR*` etc. This patch basically patches the inliner to inline such a function, which in this case happens to be an instance of the inner most enclosed function, hence has cellvars for the freevars in `__closure__`. Whilst this is probably (almost definitely) an abuse of the inliner it makes me wonder if with a little more the inliner could be extended to inline pretty much anything (I actually played with this idea a while back during the time of the closures PR)? Would such a capacity make it possible to write functionality at a higher level with all the benefits associated with such implementations? Essentially, is this a good idea/would it be useful?!

**Comment by ninegua** [comment]
@stuartarchibald Sorry for not getting back to this PR in time. It becomes outdated compared to current numba master. If you would still like to push this forward, please rebase and re-submit the PR, maybe against the `core-pa` branch, where our new code are going in. It would also be helpful to give a test case that this PR enables.

**Comment by stuartarchibald** [comment]
The core support for cells vars etc was added at a later date via other means, closing.

**Pull request closed without merging**
